project_id = "uhunetwglnzkwgpycjbu"

[functions.angel-chat]
verify_jwt = false

[functions.upload-r2]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.elevenlabs-token]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
